### ISSUE TITLE
Add automatic linting on commit

### ISSUE THREAD

**Issue by BlueSlug** [fluid-project/trivet#196] opened 2022-01-25 20:15 UTC
## Is your feature request related to a problem?
It's frustrating to forget to lint the project before committing and pushing up to remote, only to realize later on and have to make a subsequent commit with the sole purpose of correcting any linting issues. This means that the commit history is muddied with unnecessary entries, and Blame becomes more difficult to follow, among other probable issues the author has not researched.

## Describe the solution you'd like
Running the `lint-staged` task during the commit process would ensure that no linter errors make it into the commit history.

## Describe alternative solutions you've considered
A git pre-commit hook would work nicely, as well, though this is something which any developer of the project would have to remember to place into the correct directory before working on the project. This was the approach taken with the [Storytelling Tool](https://github.com/fluid-project/sjrk-story-telling/blob/5c89b9092fbfc8eb04b83f96b73d5e12c0d136ba/pre-commit), though it didn't have great cross-environment compatibility, and any time the remote was cloned it had to be re-copied.

## Additional context or notes
N/A

**Comment by greatislander** [comment] 2022-01-26 13:11
One note about this: we would need to work around `fluid-lint-all` to do this. The approach taken with We Count was to use [Husky](https://www.npmjs.com/package/husky) to configure a git pre-commit hook for [lint-staged](https://www.npmjs.com/package/lint-staged). The way this works is that you define a blob, e.g. `*.scss`, and a command to lint files which match that blob, which sets up lint-staged to run `<command> <filepath>` for each matching file. So for SCSS files, one would need to use Stylelint directly, as the resulting command is `stylelint somefile.scss`. `fluid-lint-all` can't be used to lint a single file by definition. This makes me wonder if perhaps moving away from `fluid-lint-all` to individual linters might make sense for Trivet but I'd be keen to hear other perspectives.

**Comment by greatislander** [comment] 2022-01-26 13:11
cc: @jobara @amb26 @the-t-in-rtf

**Comment by jobara** [comment] 2022-01-26 15:15
My personal preference is to not force linting at these stages. It depends on your personal workflow/style as you may want to be able to commit intermediate stages and have those tracked in history or decide to squash those down into something cleaner. Having this as optional would be useful. 

Regarding moving away from fluid-lint-all, I'll defer to @amb26 and @the-t-in-rtf. I wonder if there can be a feature added to fluid-lint-all to target specific files and/or linters for cases like this.

**Comment by greatislander** [comment] 2022-01-26 15:32
> My personal preference is to not force linting at these stages.

Turning off lint on commit could certainly be an option but providing the configuration would be great for those who want it.

> I wonder if there can be a feature added to fluid-lint-all to target specific files and/or linters for cases like this.

I don't know what the benefit would be to piping a linting tool through `fluid-lint-all` for the purpose of linting a single file. It seems contrary to the purposes of `fluid-lint-all`, namely, to run all your linters on all lintable files as a batch.

**Comment by BlueSlug** [comment] 2022-01-28 05:39
I've discovered that the [`husky` npm package](https://www.npmjs.com/package/husky) is already configured and runs both `fluid-lint-all` and [`commitlint`](https://www.npmjs.com/package/@commitlint/config-conventional) as a pre-commit hook, work added in #14.

Please feel free to either close this issue or to leave open it as a venue to discuss whether Husky should be left in or removed.

**Comment by the-t-in-rtf** [comment] 2022-02-01 08:52
Seems like you figured out what you needed, but I just wanted to respond.

By design, the checks in fluid-lint-all are not all or nothing.  Although some projects will be fine with a single configuration for everything, I can easily imagine cases in which you'd want different checks/rules for some content regardless of the file type.  Test fixtures are a good example, another would be forked copies of third-party code.  Although lots of us opt those out of checks altogether, you should also be able to check content more or less rigorously as needed.

One way of doing this is to create [a separate config file](https://github.com/fluid-project/fluid-lint-all#configuration) for the content you want to check differently, and then call fluid-lint-all using the `configFile` option.

**Comment by greatislander** [comment] 2022-02-01 12:51
I'm going to close this issue as per https://github.com/fluid-project/trivet/issues/196#issuecomment-1023904393.

**Closed by greatislander** 2022-02-01 12:51 UTC
Labels: enhancement
